### ISSUE TITLE
aliasing in scidbpy

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#114]
@apoliakov 
How do we currently provide the alias in the example cross join below?
 ```
  KG_VARIANT = db.arrays.KG_VARIANT
  selection = db.filter(KG_VARIANT, "chromosome_id=6 and end >= 55000000 and start <= 56000000")
  KG_GENOTYPE  = db.arrays.KG_GENOTYPE
  gt_selection = db.filter(KG_GENOTYPE, "allele_1=true or allele_2=true")
  gt_selection = db.cross_join**(gt_selection as x, selection as y, x.chromosome_id, y.chromosome_id, x.start, y.start, x.end, y.end, x.alternate_id, y.alternate_id)**
  print(gt_selection)
```

**Comment by apoliakov** [comment]
@rvernica this was part of an early spec using `%` but looks like not in yet. Can you estimate how long it would take to do?

**Comment by jrivers96** [comment]
We had the aliasing detailed out in our SciDB-Py architecture doc, but we did not get to implementing it yet.  It might look like the below. 

```
  KG_VARIANT = db.arrays.KG_VARIANT
  selection = db.filter(KG_VARIANT, "chromosome_id=6 and end >= 55000000 and start <= 56000000")
  KG_GENOTYPE  = db.arrays.KG_GENOTYPE
  gt_selection = db.filter(KG_GENOTYPE, "allele_1=true or allele_2=true")
  gt_selection = db.cross_join(gt_selection % 'x', selection % 'y', "x.chromosome_id, y.chromosome_id, x.start, y.start, x.end, y.end, x.alternate_id, y.alternate_id")
  print(gt_selection)
```

**Comment by rvernica** [comment]
I just added support for `%` in 237ff87

**Comment by jrivers96** [comment]
This does not work for python 3. The same repro case will work. 

``
db = connect(scidb_url="https://localhost:8083", scidb_auth=('root','Paradigm4'), verify=False)
 
db.iquery('store(build(<x:int64>[i=0:1], i), foo)')
tmp_operator_class1 = db.apply(db.arrays.foo,'xx','x')
tmp_operator_class2 = db.apply(db.arrays.foo,'yy','x')
db.cross_join(tmp_operator_class1 % 'f1', tmp_operator_class2 % 'f2', 'f1.i', 'f2.i')[:]
``

**Comment by rvernica** [comment]
I can't reproduce it:
```python
> ipython
Python 3.6.2 (default, Oct  2 2017, 16:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scidbpy

In [2]: db = scidbpy.connect()

In [3]: tmp_operator_class1 = db.apply(db.arrays.foo,'xx','x')

In [4]: tmp_operator_class2 = db.apply(db.arrays.foo,'yy','x')

In [5]: db.cross_join(tmp_operator_class1 % 'f1', tmp_operator_class2 % 'f2', 'f1.i', 'f2.i')[:]
Out[5]: 
array([(0, (255, 0), (255, 0), (255, 0), (255, 0)),
       (1, (255, 1), (255, 1), (255, 1), (255, 1))],
      dtype=[('i', '<i8'), ('x', [('null', 'u1'), ('val', '<i8')]), ('xx', [('null', 'u1'), ('val', '<i8')]), ('x_1', [('null', 'u1'), ('val', '<i8')]), ('yy', [('null', 'u1'), ('val', '<i8')])])
```

The original commit includes a [test](https://github.com/Paradigm4/SciDB-Py/blob/237ff879a42148fe34e4ec9b71f3999476e15429/scidbpy/__init__.py#L309) similar to the code above, which is executed by TravisCI on both Python 2 and Python 3.

Are you using SciDB-Py from GitHub (see [docs](https://github.com/Paradigm4/SciDB-Py#installation))? This change is not included in the PIP package yet.

If you still get an error, let me know the error and your exact Python 3 version.

**Comment by jrivers96** [comment]
My python notebook was most likely not grabbing the latest version of the package. It seems to work properly. Thank you!
