### ISSUE TITLE
Dimension part of schema does not print correctly

### ISSUE THREAD

**Issue by jriv96** [Paradigm4/SciDB-Py#128]
The print statement operating on Schema doesn't give me the correctly formatted SciDB compatible schema string. 

```
    from scidbpy import Dimension
    from scidbpy import Attribute
    from scidbpy import Schema

    temp_dimension = Dimension.fromstring('row=0:*')
    temp_array = Schema('', Attribute('x','int64'), temp_dimension)
    print(temp_array)
```

`<x,int64,False,None,None> [row; 0; *; None; None]`

**Comment by rvernica** [comment]
The `Schema` object is not constructed correctly. The second and third arguments need to be lists. So, not one attribute or one dimension, but a list of attributes or dimensions. This will work as expected:
```python
>>> temp_array = Schema('', (Attribute('x','int64'), ), (temp_dimension, ))
>>> print(temp_array)
<x:int64> [row=0:*]
```
or more explicit:
```python
>>> temp_array = Schema(name='', atts=(Attribute('x','int64'), ), dims=(temp_dimension, ))
```

**Comment by jrivers96** [comment]
Sorry about that. Didn't see the comma. I've been looking at my screen too long.
