### ISSUE TITLE
nulls in scidb format string

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#129]
Why do the nulls show up in the below scidbpy string and not for the int64s? Is this a scidb format item? 
```
temp_array.atts_fmt_scidb
'(int64, int64, int64, int64, float **null,** float **null**, float **null**)'
```

```
print(temp_array)
<study_id:int64 NOT NULL,x:int64 NOT NULL,y:int64 NOT NULL,z:int64 NOT NULL,R:float NOT NULL,G:float NOT NULL,B:float NOT NULL> [row=0:*]
```

```
temp_array.pprint()
<study_id:int64 NOT NULL,x:int64 NOT NULL,y:int64 NOT NULL,z:int64 NOT NULL,R:float NOT NULL,G:float NOT NULL,B:float NOT NULL> [row=0:*]
       name class   type nullable start end overlap chunk
0  study_id  attr  int64    False                        
1         x  attr  int64    False                        
2         y  attr  int64    False                        
3         z  attr  int64    False                        
4         R  attr  float    False                        
5         G  attr  float    False                        
6         B  attr  float    False                        
7       row   dim  int64              0   *    None  None
```

**Comment by rvernica** [comment]
In general `null` will show up if the attribute is nullable. The binary representation will contain a null byte.

For your example it shouldn't. I tried it and it does not:
```python
>>> s = scidbpy.schema.Schema.fromstring('<study_id:int64 NOT NULL,x:int64 NOT NULL,y:int64 NOT NULL,z:int64 NOT NULL,R:float NOT NULL,G:float NOT NULL,B:float NOT NULL> [row=0:*]')
>>> s.pprint()
<study_id:int64 NOT NULL,x:int64 NOT NULL,y:int64 NOT NULL,z:int64 NOT NULL,R:float NOT NULL,G:float NOT NULL,B:float NOT NULL> [row=0:*]
       name class   type nullable start end overlap chunk
0  study_id  attr  int64    False                        
1         x  attr  int64    False                        
2         y  attr  int64    False                        
3         z  attr  int64    False                        
4         R  attr  float    False                        
5         G  attr  float    False                        
6         B  attr  float    False                        
7       row   dim  int64              0   *    None  None
>>> s.atts_fmt_scidb
'(int64, int64, int64, int64, float, float, float)'
```

**Comment by jrivers96** [comment]
strange. I'll upgrade shim and see if that gives a different result.

**Comment by rvernica** [comment]
This example does not depend on Shim or SciDB. It is just local Python code, no interaction with SciDB.

**Comment by jrivers96** [comment]
```
    array_schema = '<R:float, G:float, B:float>[study_id=0:*:0:1; x=0:*:0:100; y=0:*:0:100; z=0:*:0:100]'
    temp_schema = Schema.fromstring(array_schema)
    temp_schema.make_dims_atts()
    temp_schema
    print(temp_schema.atts_fmt_scidb)
```
Schema(name=None, atts=(Attribute(name='study_id', type_name='int64', not_null=True, default=None, compression=None), Attribute(name='x', type_name='int64', not_null=True, default=None, compression=None), Attribute(name='y', type_name='int64', not_null=True, default=None, compression=None), Attribute(name='z', type_name='int64', not_null=True, default=None, compression=None), Attribute(name='R', type_name='float', not_null=False, default=None, compression=None), Attribute(name='G', type_name='float', not_null=False, default=None, compression=None), Attribute(name='B', type_name='float', not_null=False, default=None, compression=None)), dims=(Dimension(name='study_id', low_value=0, high_value='*', chunk_overlap=0, chunk_length=1), Dimension(name='x', low_value=0, high_value='*', chunk_overlap=0, chunk_length=100), Dimension(name='y', low_value=0, high_value='*', chunk_overlap=0, chunk_length=100), Dimension(name='z', low_value=0, high_value='*', chunk_overlap=0, chunk_length=100)))

`(int64, int64, int64, int64, float null, float null, float null)`

**Comment by jrivers96** [comment]
I think I'm confused. I thought atts_fmt_scidb was meant to be used for use with the input operator. I was expecting NOT NULL to be printed out.

**Comment by rvernica** [comment]
`atts_fmt_scidb` is used as the `format` string for operators that take a `format` string attribute like `input` and `save`. The result you get is correct, `R:float` is a nullable attribute and will show up as `float null`, while `study_id=0:*` is a not nullable and it will show up as `int64`.
