### ISSUE TITLE
latest scidbpy master version compatibility with 17.1 shim

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#130]
I'm running 17.1 SciDB / 17.1 Shim on my VM and receiving the below errors on the latest version of scidbpy in master. Do I need an updated shim? Is there a reason I shouldn't be using the latest development version of scidbpy? 

``
db.create_array(meta_array, meta_schema)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/scidbpy/db.py", line 711, in __call__
    upload_schema=self.upload_schema)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/scidbpy/db.py", line 352, in iquery
    self._shim(Shim.execute_query, query=query)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/scidbpy/db.py", line 432, in _shim
    req.raise_for_status()
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/models.py", line 935, in raise_for_status

 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Invalid session ID for url: http://localhost:8080/execute_query?id=43&query=create_array%28FLIM_IMAGE_META%2C+%3Cstudy_name%3Astring%2C+description%3Astring%3E%5Bstudy_id%3D0%3A%2A%3A0%3A1%5D%2C+False%29
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /release_session?id=43 HTTP/1.1" 404 None
Traceback (most recent call last):
```

**Comment by rvernica** [comment]
`id=43` tells me you are using an older Shim, before session authentication. Newer Shim has longer, non-sequential, alpha numeric session IDs, for example `id=2jig3edpbf1yiszct03atlwg7vy9k5l2`.

You can try upgrading the Shim to the `v16.9-session-auth` or `master` branch (whichever compiles) or downgrade SciDB-Py to the `v16.9` branch or just `pip install scidb-py==16.9.2`. We did not test much with `17.1`, we mainly focused on `16.9` and `18.1`.

My recommendation would be to upgrade Shim. You don't want to downgrade SciDB-Py as the master has many fixes and new features.
