### ISSUE TITLE
Hanging cancel-queries

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDB-Py#132]
I run a long-running query with scidb-py in the notebook: make any large array you want and then say something like:
```db.iquery('op_count(sort(ARRAY))')```

Then I hit "stop" in the notebook to get the cancellation.

I'm seeing the cancellation goes through but, after that, there appear to be "orphaned" cancel queries:
```
$ iquery -aq "list('queries')"
{inst,n} query_id,coordinator,query_string,creation_time,error_code,error,idle,user_id,user
{0,0} '0.1530910727951888405',0,'cancel(\'0.1530910722871112974\')','2018-07-06 20:58:47',0,'Success',false,1,'scidbadmin'
{0,1} '0.1530910749690395837',0,'cancel(\'0.1530910744307854527\')','2018-07-06 20:59:09',0,'Success',false,1,'scidbadmin'
...
```

This is a new behavior. Looks like something isn't getting cleaned up? It doesnt happen if I cancel the query using iquery for example. Not sure if it's a scidb-py or a shim issue?

**Comment by rvernica** [comment]
I wander what those query IDs correspond to. There should be only one [cancel request](https://github.com/Paradigm4/SciDB-Py/blob/7d1f533e843f1df68306f7f13f53eb1ff48de64a/scidbpy/db.py#L460) sent from SciDB-Py on that specific session. SciDB-Py *does not* have a specific query ID (just a session ID). Shim is the one issuing the specific `cancel` calls on the specific *query IDs* which should be only one per session at a time.

Could it be that when you hit "stop" you are stopping multiple SciDB-Py sessions and each issue a cancel request to Shim? And just to clarify, by "stop" you mean you are *interrupting the Python Notebook Kernel*, right?

Also worth mentioning is that when the Python session terminates, SciDB-Py tries to erase the temporary arrays it created during the session.

**Comment by apoliakov** [comment]
Yeah I just have one Jupyter notebook with one `db` object and I hit the "stop" button to get this while a query is running.

**Comment by rvernica** [comment]
I'm having trouble reproducing this. Here is the Python Notebook code I used:
```python
db.build('<x:double>[i=1:10000;j=1:10000]', 'random()').store('big')
```
then
```python
db.iquery('op_count(sort(big))')
```
I interrupt it by hitting the "Stop" button.

---
In the Shim log I see:
```
Jul 18 02:36:25 shim: /execute_query
Jul 18 02:36:25 shim: execute_query[isl2bb]: execute, scidb[0] 0x7f06c4042e10, scidb[1] 0x7f06c4042e40, query store(build(<x:double>[i=1:10000;j=1:10000], random()), big)
Jul 18 02:36:25 shim: execute_query[isl2bb]: execute, qid 0.1531881385327508029
Jul 18 02:36:48 shim: execute_query[isl2bb]: done

Jul 18 02:37:58 shim: /execute_query
Jul 18 02:37:58 shim: execute_query[isl2bb]: execute, scidb[0] 0x7f06c4042e10, scidb[1] 0x7f06c4042e40, query op_count(sort(big))

Jul 18 02:37:58 shim: execute_query[isl2bb]: execute, qid 0.1531881478319353666
Jul 18 02:38:03 shim: /cancel
Jul 18 02:38:03 shim: cancel[isl2bb]: execute, qid 0.1531881478319353666, scidb[1] 0x7f06c4042e40, query cancel('0.1531881478319353666')
Jul 18 02:38:03 shim: cancel[isl2bb]: result 
```
In for `list('queries')` I get:
```bash
> iquery -aq "list('queries')"
{inst,n} query_id,coordinator,query_string,creation_time,error_code,error,idle,user_id,user
{0,0} '0.1531881478319353666',0,'op_count(sort(big))','2018-07-18 02:37:58',62,'Query 0.1531881478319353666 was cancelled',false,1,'scidbadmin'
{0,1} '0.1531881483995598332',0,'cancel(\'0.1531881478319353666\')','2018-07-18 02:38:03',0,'Success',false,1,'scidbadmin'
{0,2} '0.1531881497894874665',0,'list(\'queries\')','2018-07-18 02:38:17',0,'Success',false,1,'scidbadmin'
{1,0} '0.1531881478319353666',0,'','2018-07-18 02:37:58',62,'Query 0.1531881478319353666 was cancelled',false,1,'scidbadmin'
{1,1} '0.1531881483995598332',0,'','2018-07-18 02:38:03',0,'Success',false,1,'scidbadmin'
{1,2} '0.1531881497894874665',0,'','2018-07-18 02:38:17',0,'Success',false,1,'scidbadmin'
```
and a little later I get this in the Shim log:
```
Jul 18 02:38:48 shim: execute_query: ERROR execute, isl2bb: SystemException in file: src/query/Query.cpp function: handleAbort line: 644 Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_QUERY_CANCELLED Error description: Query processor error. Query 0.1531881478319353666 was cancelled. Failed query id: 0.1531881478319353666
```
and this for `list('queries')`:
```bash
> iquery -aq "list('queries')"
{inst,n} query_id,coordinator,query_string,creation_time,error_code,error,idle,user_id,user
{0,0} '0.1531881483995598332',0,'cancel(\'0.1531881478319353666\')','2018-07-18 02:38:03',0,'Success',false,1,'scidbadmin'
{0,1} '0.1531881538825262357',0,'list(\'queries\')','2018-07-18 02:38:58',0,'Success',false,1,'scidbadmin'
{1,0} '0.1531881483995598332',0,'','2018-07-18 02:38:03',0,'Success',false,1,'scidbadmin'
{1,1} '0.1531881538825262357',0,'','2018-07-18 02:38:58',0,'Success',false,1,'scidbadmin'
```

If you can still reproduce this, then getting the Shim log might help us figure it out.

**Comment by rvernica** [comment]
Fixed in Shim master
