### ISSUE TITLE
Arrow 0.9.0 dependency and Python 3.7

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#135]
`accelerated_io_tools` depended on Arrow `0.9.0`. As such we made SciDB-Py depend on `pyarrow==0.9.0` https://github.com/Paradigm4/SciDB-Py/blob/f7167fd0ce87905f617e05e589c008fe6e85bdff/requirements.txt#L5

`pyarrow` is not straightforward to compile and using pre-compiled packages is preferred. For `pyarrow==0.9.0` pre-compiled packages are available for Python up to `3.6` https://pypi.org/project/pyarrow/0.9.0/#files Current version of Python is `3.7` and of `pyarrow` is `0.12.1`.

Recent OS come with Python version is `3.7`. On these systems, getting `pyarrow==0.9.0` is not convenient and installation could easily fail. As such, SciDB-Py installation would fail. I ran into this twice on two different systems and in both cases I abandoned installing SciDB-Py.

Here are some options:
1. Update `accelerated_io_tools` and SciDB-Py to work with latest Arrow and `pyarrow`, respectively. This might require some time since there have been changes to the Arrow API. I think this is the best option for the future.
1. It seems that data written by Arrow `0.9.0` could be read by newer `pyarrow` versions. There is no hard proof for this yet, but it is the belief of the Arrow [developers](http://mail-archives.apache.org/mod_mbox/arrow-dev/201903.mbox/%3CCAJPUwMDd23%2BHWPX%3D-3oykceeUJocjhN8%3D-c7Sw3sQ%2BM3V%2B9NVA%40mail.gmail.com%3E).
1. We could remove the dependency on `pyarrow` from SciDB-Py. The user of the library will have to install `pyarrow` before `use_arrow = True` can be used. This might make the library harder to use for the user since not everything is ready out of the box.

**Comment by ksens** [comment]
@rvernica 

Just wanted to add that I also faced something similar while trying to set up a `scidb + conda for python3 + scidb-py + flask` stack. I tried a lot of tricks (this was a few weeks back, so I do not remember exactly what I tried) but eventually gave up. 

In the project where I was planning to use scidb-py, we later switched to a `scidb + scidbR` stack so we were able to ignore this problem for now.

**Comment by rvernica** [comment]
In some chases newer PyArrow versions can be used. Tests have completed successfully. The PyArrow version restriction in SciDB-Py has been relaxed.

* PyArrow dependency in SciDB-Py has be updated in f52b9f2ab6b4d07cb24542ce2f5689be0bb966c8
* Tests available in accelerated_io_tools for Arrow have been ran successfully for [different versions](https://github.com/Paradigm4/accelerated_io_tools/pull/34/commits/e3bdf60704de7c14bcf503fdaa528044454f7a32) of Python
