### ISSUE TITLE
scidb hangs indefinitely when executing certain `mquery` query via scidb-Py

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDB-Py#139]
@rvernica @apoliakov 

(Follow up from https://paradigm4.atlassian.net/browse/SDB-6835)

Could you take a look at this? 

I have an `mquery` query (scidb 19.11) that is expected to `throw` and fail. 

When executing this `mquery` query via scidb-Py, scidb hangs indefinitely. However the same query runs as expected when the query is executed via scidbR. 

Maybe this has something to do with how `/cancel` query endpoint of shim is called in scidbR, but not in scidb-Py?

### Setup

```sh
iquery -aq "create array temp1 <val:string, x:uint8>[i=0:1]"
```

### First we run our query via SciDB-R and check the expected behaviour

```R
# R
library(scidb)
db = scidbconnect()
iquery(db, "mquery(insert(apply(build(<val:string>[i=0:1], i), x, throw('haha')), temp1))")
# Fails with proper error
```

If we check list of queries, we see that all queries have cleared out
```sh
iquery -aq "list('queries')"
# {inst,n} query_id,coordinator,query_string,creation_time,error_code,error,idle,user_id,user
# {0,0} '0.1583830377593319800',0,'list(\'queries\')','2020-03-10 08:52:57',0,'Success',false,1,'scidbadmin'
# {1,0} '0.1583830377593319800',0,'','2020-03-10 08:52:57',0,'Success',false,1,'scidbadmin'
```

### Error seen when using scidb-py

```py
# Python
from scidbpy import connect
db = connect()
db.iquery("mquery(insert(apply(build(<val:string>[i=0:1], i), x, throw('haha')), temp1))", fetch=False)
# Fails with proper error
```

But if we check the list of queries, the query is not canceled. 
```sh
iquery -aq "list('queries')"
# {inst,n} query_id,coordinator,query_string,creation_time,error_code,error,idle,user_id,user
# {0,0} '0.1583830064798236900',0,'mquery(insert(apply(build(<val:string>[i=0:1], i), x, throw(\'haha\')), temp1))','2020-03-10 08:47:44',26,'Illegal operation: haha',false,1,'scidbadmin'
# {0,1} '0.1583830082465078500',0,'list(\'queries\')','2020-03-10 08:48:02',0,'Success',false,1,'scidbadmin'
# {1,0} '0.1583830064798236900',0,'','2020-03-10 08:47:44',0,'Success',false,1,'scidbadmin'
# {1,1} '0.1583830082465078500',0,'','2020-03-10 08:48:02',0,'Success',false,1,'scidbadmin'
```

### Cleanup

```sh
hung_query_id=`iquery -otsv -aq "project(filter(list('queries'), regex(query_string, 'mquery(.*)')), query_id)"`
iquery -aq "cancel('$hung_query_id')"
iquery -aq "remove(temp1)"
```

**Comment by rvernica** [comment]
The fix is in the master. It it is all good, I'm release a new version of the package. Let me know.

**Comment by ksens** [comment]
Beautiful! 

Works perfectly. 

You might consider marking this important change with a package version change https://github.com/Paradigm4/SciDB-Py/blob/master/scidbpy/__init__.py#L1043

**Comment by rvernica** [comment]
SciDB-Py `19.3.3` has been released and pushed to PyPI. It includes this fix.
