### ISSUE TITLE
Any way to turn off warning?

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDB-Py#140]
@rvernica 

My application logs are filled with this kind of warning:

```
UserWarning: 3 type(s) promoted for null support
```

Is there a way to turn this off? The code that leads to this was almost any `iquery` fetch statement:

```py
db.iquery(query = '<any_query>', fetch=True)
```

**Comment by ksens** [comment]
Seeing https://github.com/Paradigm4/SciDB-Py/issues/134, I tried `use_arrow` but got some errors. Will update the ticket soon.

**Comment by rvernica** [comment]
There is a note about this types of warnings in the [docs](http://paradigm4.github.io/SciDB-Py/guide.html). Here is the relevant snippet:

> Attributes with null-able types are promoted as per Pandas promotion scheme During such promotions, precision loss might occur. The user is notified about this via a UserWarning. If desired, such warnings can be disabled as follows:

```
>>> import warnings
>>> warnings.filterwarnings('ignore', category = UserWarning)
```
