### ISSUE TITLE
Suggestions for documentation updates

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDB-Py#151]
Suggesting some doc updates:

`1`. 

Need documentation for `result_size_limit` parameter in the Github pages doc (http://paradigm4.github.io/SciDB-Py/). Something on the lines of:

```py
from scibdpy import connect
db = connect(
  'http://127.0.0.1:8080/', 
   scidb_auth=(creds['user-name'], creds['user-password']),
   result_size_limit=100*1024)
``` 

`2`. 

Would be good to get rid of the warning at the top of https://paradigm4.github.io/SciDB-Py/index.html. It was confusing some of our customers who were going through scidb-py documentation recently. 

It should be sufficient to keep the warning around at the legacy readthedocs site https://scidb-py.readthedocs.io/en/v16.9-legacy/

**Comment by rvernica** [comment]
For (1), it was documented in the code but the docs haven't been regenerated in a while. Done now.

**Comment by rvernica** [comment]
The updated docs are online now. The `result_size_limit` is documented here https://paradigm4.github.io/SciDB-Py/api.html#scidbpy.db.DB

**Comment by ksens** [comment]
Thanks @rvernica !
