### ISSUE TITLE
Would like to arrow stream (or a generator that yields record batches) from `iquery()` [low-prio]

### ISSUE THREAD

**Issue by agvandervelde** [Paradigm4/SciDB-Py#159]
Hi! I'd like to propose an additional argument that make `iquery()` return a reference to the stream, or a generator that yields record batches, rather than the full pandas data.frame. The use case here is that I'd like to be able "forward" the stream from a REST API, record batch by record batch. A follow-up query would be if there's a way to control batch size.

ref: https://github.com/Paradigm4/SciDB-Py/blob/master/scidbpy/db.py#L432-L456

**Comment by rvernica** [comment]
To clarify, you would like the bytes buffer to be returned to you? 

Regarding the follow-up question, `read-bytes` in Shim takes a _bytes to read_ argument but its use is not encouraged:

> PARAMETERS n the maximum number of bytes to read and return between 0 and 2147483647.
> 
> Set n=0 to download the entire output buffer. You should almost always set n=0.
> 
> When n>0, iterative requests to read_bytes are allowed, and will return at most the next n lines of output. Use the 410 error code to detect end of file output. Don’t use this option if you can avoid it. 

http://paradigm4.github.io/shim/help.html#read_bytes

To use this we would have to implement follow-up calls to get the rest of the bytes.

**Comment by agvandervelde** [comment]
`iquery()` uses `RecordBatchStreamReader`, to read arrow streaming format, which according to the documentation is basically chunks of arrow-formatted data (record batches). `iquery` reads all record batches right away to construct a pandas data.frame, in memory. I'd like to have a way to iterate over the record batches myself instead.

**Comment by rvernica** [comment]
SciDB-Py uses Shim to query SciDB. In turn Shim creates a connection to SciDB using the SciDB API. Shim is not necessarily identical in operation as `iquery`.

**Comment by agvandervelde** [comment]
Are we talking about the same thing here? I'm referring to the `iquery()` method, specifically this part: https://github.com/Paradigm4/SciDB-Py/blob/master/scidbpy/db.py#L433

**Comment by rvernica** [comment]
We were not. Now I get it. It seems very easy. We can add a new flag `use_arrow_stream` which would return a `pyarrow.RecordBatchStreamReader` to the user. Would that suffice?

**Comment by agvandervelde** [comment]
:) yes, I think that works. thanks!
