### ISSUE TITLE
Can't seem to find any resources to install and set up SciDB

### ISSUE THREAD

**Issue by dongheuw** [Paradigm4/SciDB-Py#161]
Hi there,

I spent a few days and haven't had any luck finding any resources online to install and set up SciDB (any version!). I want to install it on Ubuntu 18.04. As I understand, SciDB-Py needs to connect to a running SciDB server, right?

Does SciDB have a community version? Does it support Ubuntu 18.04? Please help!!

Thank you,
Dong

**Comment by ksens** [comment]
@dongheuw Thanks for reaching out.. we reached out to you separately on the email listed in your github profile. Closing issue here.
