### ISSUE TITLE
Design priorities for non-numpy schemas

### ISSUE THREAD

**Issue by ChrisBeaumont** [Paradigm4/SciDB-Py#49]
This is a spinoff of the discussion in #48 

Many open issues relate to concepts in SciDB which don't have a clean analog in numpy (#7, #45, #47, #48). The general question here is how, and to what extent, should SciDB-py support arrays which don't conform to numpy arrays? 

My impression is that people want to use SciDBpy as a client interface to their databases, so they will frequently encounter non-numpy-conformable arrays. Here's my take on the design considerations
### Principle of Least Surprise

A subset of SciDB arrays _do_ conform to numpy arrays (0 origin, explicit lower/upper bounds, no nulls). As much as possible, the interface to such arrays should be indistinguishable from working with a vanilla numpy array
### Helpful error messages

If no better options exist when a user tries to do something with a non-conformable array, SciDBpy should generate a helpful error message. Under this principle, #47 and #48 raise something like an `UnsupportedSchema` exception, instead of returning the wrong answer or obscure error, respectively. 
### Explicit "conversion" routines

Some SciDB concepts can be ported over by providing utilities which "coerce" a SciDBarray into something more numpy-like. #21, for example, could be addressed by scanning the array for the longest string, and then allocating the appropriate fixed-width numpy string array. `toarray` could accept a `fill` keyword to replace NULLs with a default value (#7). A `sdbidx` property could provide an alternative interface to `__getitem__` to respect scidb origins (#45)

With sufficient conversion utilities, users should always be able to find workarounds when encountering a non-conformable array
### Generalize DataShape

This is the most difficult thing to tackle -- DataShape could be generalized to directly address issues like #47 and #48. However, lots of SciDB-py plumbing implicitly assumes 0-origins and bound arrays, so this is prone to subtle buggy behavior.

**Comment by rvernica** [comment]
Obsolete, SciDB Arrays no longer supported.
