### ISSUE TITLE
SciDB Aggregates do not behave like Numpy Aggregates

### ISSUE THREAD

**Issue by jakevdp** [Paradigm4/SciDB-Py#6]
Aggregates in scidb do not behave like numpy.

For example:

``` python
>>> import numpy as np
>>> from scidbpy import interface
>>> sdb = interface.SciDBShimInterface('localhost:8080')
>>> X = sdb.random((3, 5))
>>> print X.toarray()
[[ 0.65073782  0.99674732  0.02796667  0.55772179  0.75608707]
 [ 0.88330933  0.16776783  0.90869342  0.39415646  0.18661128]
 [ 0.4073007   0.53225481  0.54275498  0.44238137  0.54026616]]
>>> print X.min(0).toarray()
[ 0.02796667  0.16776783  0.4073007 ]
>>> print X.toarray().min(0)
[ 0.4073007   0.16776783  0.02796667  0.39415646  0.18661128]
```

This is currently by-design, because SciDB internally treats aggregate arguments this way.  Perhaps we should map SciDB-py inputs so that the results match those of numpy?  I'm not sure what would be the least confusing course.

Also, aggregates over the entire array currently return a 1-element SciDB array:

``` python
>>> X.min()
SciDBArray("not empty py1101172117644_00003<f0_min:double NULL> [i=0:0,1,0]")
```

Again, this is how it works by default within SciDB, but it's unexpected for a numpy-style interface.  Should we make these global aggregations simply return the value instead?  Note that this is precisely what we do in the case of indexing an array.

Neither of these is an implementation challenge, but simply a design question.

I'd be interested in input from @bwlewis, @teoliphant, and @pzwang.

**Comment by rvernica** [comment]
`SciDBArray` no longer supported. The library returns NumPy Arrays or Pandas DataFrames.
