### ISSUE TITLE
See which expensive schema_utils calls can be removed

### ISSUE THREAD

**Issue by ChrisBeaumont** [Paradigm4/SciDB-Py#73]
SciDB 14.12 relaxed several requirements on the chunk sizes and overlaps of the inputs to several AFL functions. SciDB-Py implemented workarounds to many of these, using functions in schema_utils to coerce schemas as appropriate. However these calculations can be expensive, and often result in evaluating temporary AFL queries. We should look to see which expensive calls can be removed.

**Comment by rvernica** [comment]
Obsolete, `schema_utils` no longer available.
