### ISSUE TITLE
On 14.12 seeing an issue with a simple "list_arrays()"

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDB-Py#76]
sdb = connect()
sdb.list_arrays()

IndexError                                Traceback (most recent call last)
<ipython-input-20-0f4823ecf0c8> in <module>()
      1 sdb = connect()
----> 2 sdb.list_arrays()

/usr/local/lib/python2.7/dist-packages/scidb_py-14.10.0.dev-py2.7.egg/scidbpy/interface.pyc in list_arrays(self, parsed, n)
    443                 arr_list = dict((a[0], a[1:])
    444                                 for a in csv.reader(splits,
--> 445                                                     quotechar=quotechar))
    446         return arr_list
    447 

/usr/local/lib/python2.7/dist-packages/scidb_py-14.10.0.dev-py2.7.egg/scidbpy/interface.pyc in <genexpr>((a,))
    442                 splits = R.findall(arr_list)
    443                 arr_list = dict((a[0], a[1:])
--> 444                                 for a in csv.reader(splits,
    445                                                     quotechar=quotechar))
    446         return arr_list

IndexError: list index out of range

**Comment by ChrisBeaumont** [comment]
@apoliakov can you confirm this still happens with the master version on github? This might have been fixed by adadc7f82d2a7974549418f8ed2e6d59ebbe8414

**Comment by alexvmarch** [comment]
Issue seems fixed in current master. I am on scidbpy version '14.12.0.dev' and scidb version 14.12 (obtained post 1/27/15).
