### ISSUE TITLE
Connect does not report to user that it is retying the connection

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#81]
Connect does not report to user that it is retying the connection. This can go on for awhile and gives the user the perception that the query is running in the database.

**Comment by jrivers96** [comment]
Success: HTTP 200 and text session ID value in text/plain payload
Failure (out of resources/server unavailable): HTTP 503
Invalid request (encrypted only -- this means auth is missing): HTTP 400
Not authorized (encrypted only): HTTP 401

Apparently, the Python package is re-trying automatically with it gets
the 503 error (out of resources). That is a bad idea IMO, and not in
the spirit of the API. It should just report the error! That gives the
user valuable information (that there are a huge number of concurrent
queries in flight).

You should modify the Python package to throw that error. It should be
up to the user program to catch that and re-try if they want to...

**Comment by rvernica** [comment]
Fixed in SciDB-Py `16.9.1`. An immediate HTTP 503 error is returned if the Shim server is out of resources.
