### ISSUE TITLE
Issues with running iquery at install and possible solutions

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDB-Py#85]
In his comment (https://github.com/Paradigm4/SciDB-Py/commit/c6d715e2a5ef439cf8164889c39d6a8be47c0e80#commitcomment-13289653), @ChrisBeaumont pointed out concerns with new approach of loading operators and macros at install time. Copying his concerns (and numbering them) here:

> 1. It relies on iquery being installed on the client machine, instead of using SciDB-Py's normal mechanism of using the shim 

> 2. This will raise an exception if the command fails. You shouldn't need a connection to SciDB in order to import SciDB-Py (for instance readthedocs won't be able to build the docs with this code)

> 3. This work should probably be done if + when the user establishes a connection to scidb. 

> 4. It should perhaps also be redone when a user loads a new plugin

Now, let's try to find a good solution to this problem by discussing here. 

Some history
==========

Initial code before my commit https://github.com/Paradigm4/SciDB-Py/commit/c6d715e2a5ef439cf8164889c39d6a8be47c0e80 was loading operators through `afldb.py` -- this was creating an issue because `load()` is not a macro in SciDB 15.7 (subsequently, unit tests that used `load()` were failing)

My commit https://github.com/Paradigm4/SciDB-Py/commit/c6d715e2a5ef439cf8164889c39d6a8be47c0e80 tried to get an updated list of operators (and macros) by invoking the shell command `iquery -aq "list('operators')"`, and then using the output to populate the AFL namespace. But this has the problems listed by @ChrisBeaumont above. 

Possible solutions
==============

1. Install with defaults, update at connect
------------------------------------------------------

This approach would use `afldb.py` at install, and get updated list of operators and macros at `connect()`. 
**Pros:** 
 - Install would work as before (i.e. prioro to commit https://github.com/Paradigm4/SciDB-Py/commit/c6d715e2a5ef439cf8164889c39d6a8be47c0e80) -- so issues 1,2 in list by @ChrisBeaumont  would be taken care of
 - Plugin operators would be available to SciDB-py
 - Operators and macros would be updated at the time of `connect()` so unit tests would also pass

**Cons:**
 - There would be an extra overhead at every `connect()`. @jrivers96 pointed out that this might be an unnecessary overhead that would result in delays at client sites who use scripts that run `connect()` very frequently

2. Install with defaults, user updates explicitly
------------------------------------------------------------

This approach would use `afldb.py` at install, so user would get a default set of operators provided by `afldb.py`. An updated list of operators and macros would have to be retrieved by an explicit function (say `update_afl()`) call by the user. 
**Pros:** 
 - Issues 1,2 in list by @ChrisBeaumont would be solved
 - No extra overhead as pointed out by @jrivers96 
 - Plugin operators/ macros would be available to SciDB-py after the manual function call by user

**Cons:**
 - This solution relies on the user to run a process manually
 - Unit tests would fail till user manually updates the list of operators and macros

Which solution sounds better? Looking forward to inputs. After a consensus, will send a pull request with my code changes so that it can be reviewed. Thanks.

**Comment by ChrisBeaumont** [comment]
I'm in favor of approach 1, since it's less error prone. I don't think the overhead of connect() is really a con for 2 reasons:

  * The overhead has to be paid *sometime* (in the current codebase, it's paid at import time). You could also cache the results after the first connect(), so that subsequent connects have no overhead (although usually people only connect once per session)
  * the overhead is equivalent to 1 query roundtrip, with a very small payload. Presumably you will spend much more time issuing interesting (and bulkier) queries, so the relative overhead of connect is negligible.

**Comment by jrivers96** [comment]
I like the option of caching the result.

Many of our customers utilize prebuilt scripts(each has a connect) hundreds
or thousands of times per day. They expect short query  result back
quickly.  When you only connect once per session, you are generally using
SciDB interactively.

**Comment by ksens** [comment]
Thanks. OK, so let's go for option 1 with caching. First, I will try to implement approach 1 without caching, and then add caching. 

I am looking through the code to try and figure out the best location to add this functionality. 

`interface.py` defines `connect()` which has the following code:
```Python
    return SciDBShimInterface(url, user=username, password=password)
```

Now, `SciDBShimInterface` is an inherited class of `SciDBInterface`, which has the following property defined on it:
```Python
    @property
    def afl(self):
        if not hasattr(self, '_afl'):
            from .afl import AFLNamespace
            self._afl = AFLNamespace(self)
        return self._afl
```

Next, `AFLNamespace` is defined in `afl.py` and has the following `__init__` defined on it:
```Python
    def __init__(self, interface):
        for op in operators:
            if op['name'] in DEPRECATED:
                continue
            setattr(self, op['name'], register_operator(op, interface))

        for name, op in infix_functions:
            setattr(self, name, register_infix(name, op))
```

I assume that this is where the actual linking of the operators is happening, right? 

Anyway, now that the preface is done, let's try to find out a good way to implement the change. Here's a solution I have in mind:

 - Change the code within `interface.py >> connect()` function from:

```Python
    return SciDBShimInterface(url, user=username, password=password)
```

 - to:
```Python
    shimInterf = SciDBShimInterface(url, user=username, password=password)
    curList = dir(shimInterf.afl)							# store the list of AFL operators and infix functions that have been imported through afldb.py
    opList = shimInterf.afl.list("'operators'").toarray()	# query the connected SciDB engine to view the currently supported list of operators 
																# (e.g. operators added through custom plugins will be viewable here)
    macroList = shimInterf.afl.list("'macros'").toarray()	# query the connected SciDB engine to view the list of SciDB macros
    ops = [op for op, source in opList]
    macros = [macro for macro, source in macroList]
    
    for op in ops+macros:
		if op in curList:
			continue
		opEntry = dict(name=op, signature=[], doc='')
		setattr(shimInterf.afl, op, register_operator(opEntry, shimInterf))

    return shimInterf
```

Of course, I found that this requires a lot of other changes to code (especially to make sure that `register_operator()` is visible to `interface.py`). I will share my current change-set through a branch / pull request. 

Let me know if you have any simpler solutions to implementing approach 1.

**Comment by ChrisBeaumont** [comment]
I suggest a slightly different organization:

add a function to afl.py that looks like

```python
def update_operators(interface):
  <build a list of {name: 'name', signature=[], doc=''}>
  for op in new_operators:
        operators.append(op)
```

Then, in interface:connect:

```python

def connect(...):
    ...
    result = SciDBShimINterface(...)
    from scidbpy.afl import update_operators
    update_operators(result)
    return result
```

**Comment by ksens** [comment]
Hi @ChrisBeaumont :

Tried implementing your solution at https://github.com/ksens/SciDB-Py/tree/updateOps_append

You can see the last two commits ahead of master at Paradigm4 to see my changes:
 - The first commit removes the calls to iquery and reverts back to usign `afldb.py` only
 - The second commit implements your solution

Now, after doing just this, if I try `python setup.py install`, and run the following:
```Python
from scidbpy import connect
sdb = connect('http://localhost:8080')
```
I still do not see `load()` to be visible yet e.g. by trying `sdb.afl.load`, I get: 
```Python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8f3563ddebc3> in <module>()
----> 1 sdb.afl.load

AttributeError: 'AFLNamespace' object has no attribute 'load'
```

But when I run `connect()` the second time, `load()` becomes visible after that. 
```Python
In [5]:
sdb.afl.load
Out[5]:
<function scidbpy.afl.load>
```

Here is my understanding: 
 - When I run `python setup.py install`, the **original** list of `operators` is retrieved from `afldb.py`
 - After running `connect()`, `setattr` is called on the **original** list of `operators`. So `load()` is not available yet.
 - Next, `operators` is **appended** with the list of macros and operators, but `setattr` is not called yet. 
 - When I run `connect()` the second time, `setattr` is called on the new/**appended** list of `operators` 

PS: BTW I did not understand your comment about touching `interface.afl` -- where might I have done that? And where do I do `del interface._afl`?

**Comment by ksens** [comment]
Hi @ChrisBeaumont 

I did a little more investigation after my previous comment, and found a solution merging your idea of the code placement, and my idea of using `setattr`. 

I put in a pull request -- can you take a look?

- Pull request link: https://github.com/Paradigm4/SciDB-Py/pull/86

**Comment by ksens** [comment]
Pull request https://github.com/Paradigm4/SciDB-Py/pull/86 merged
