### ISSUE TITLE
Add support for the /upload service

### ISSUE THREAD

**Issue by rschutt** [Paradigm4/SciDB-Py#89]
The new /upload service is faster and simpler to use.

**Comment by rvernica** [comment]
The new version of the library, see [devel branch](https://github.com/Paradigm4/SciDB-Py/tree/devel), uses the [/upload](https://github.com/Paradigm4/SciDB-Py/blob/01a0717081befd65582b19b1ae8a72e3d7fae072/scidbpy/db.py#L36) service.
